name: Deploy to Netlify
on:
  issues:
    types: [opened, deleted, closed, reopened, labeled, unlabeled, milestoned, demilestoned]
  issue_comment:
    types: [created, edited, deleted]
  milestone:
    types: [created, edited, deleted]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger shape-up site deploy on Netlify
      run: |
        curl -X POST "https://api.netlify.com/api/v1/sites/$NETLIFY_SHAPEUP_SITE_ID/builds" -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SHAPEUP_SITE_ID }}
    - name: Trigger AsyncAPI site deploy on Netlify (Roadmap update)
      run: |
        curl -X POST "https://api.netlify.com/api/v1/sites/$NETLIFY_ASYNCAPI_SITE_ID/builds" -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_ASYNCAPI_SITE_ID }}
